version: '3.8'
services:
  lia-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT:-4200}:${CONTAINER_PORT:-8080}"
    restart: unless-stopped
    environment:
      - CONTAINER_PORT=${CONTAINER_PORT}
      - HOST=${HOST}
    networks:
      - lia-network
    # Add healthcheck using environment variables
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://${HOST:-localhost}:${CONTAINER_PORT:-8080}"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  lia-network:
    name: lia-network
